name: Build and Deploy
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  fetch-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and and fetch
        run: |
          npm install
          npm start

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist

